Plugin Name: ExamplePlugin
App Version: 3.6.2
Server Main Class: com.growcontrol.plugins.exampleplugin.server.ExamplePluginServer
Client Main Class: com.growcontrol.plugins.exampleplugin.client.ExamplePluginClient
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []
