Plugin Name: ExamplePlugin
Plugin Version: 3.6.1
Server Main: com.growcontrol.plugins.exampleplugin.server.ExamplePlugin.class
Client Main: com.growcontrol.plugins.exampleplugin.client.ExamplePlugin.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []