Plugin Name: ${project.name}
Plugin Version: ${project.version}
App Version: 3.6.2
Commit: ${git.commit.id}
Server Main Class: com.growcontrol.plugins.exampleplugin.server.gcExamplePlugin_Server
Client Main Class: com.growcontrol.plugins.exampleplugin.client.gcExamplePlugin_Client
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
