Plugin Name: ExamplePlugin
Plugin Version: 3.6.1
Main Class:
  - com.growcontrol.plugins.exampleplugin.server.ExamplePluginServer.class
  - com.growcontrol.plugins.exampleplugin.client.ExamplePluginClient.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []
