Plugin Name: ExamplePlugin
App Version: 3.6.2
Server Main Class: com.growcontrol.plugins.exampleplugin.server.gcExamplePlugin_Server
Client Main Class: com.growcontrol.plugins.exampleplugin.client.gcExamplePlugin_Client
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []
